// @vitest-environment jsdom
import { beforeEach, it, expect, vi } from "vitest";
import { render, fireEvent, cleanup, waitFor, screen } from "@testing-library/react";
import { makeStores } from "../../../data/registry";
import { LinkGroups } from "../../linkGroups";
import type { ChartApiFacade } from "../../../render/chart/ChartApiFacade";
import { getTvChrome } from "../../../render/chart/tvTheme";
import { initiateChartRiskEntry, type RiskEntryTemplate } from "../../exec/actionTemplate";
import { ChartRiskEntry } from "./ChartRiskEntry";
const template: RiskEntryTemplate = { kind: "risk", id: "r", label: "Risk", mode: "Dollar", value: 100, buyCushion: { value: 0, unit: "$" }, sellCushion: { value: 0, unit: "$" } };
function mount(auto = false) {
    const stores = makeStores();
    stores.exec.apply({ kind: "snapshot", topic: "exec.status", payload: { masterArmed: true, venues: [{ venue: "sim", broker: "sim", connected: true, positionDataReady: true }] } });
    stores.exec.apply({ kind: "snapshot", topic: "exec.account", payload: { venue: "sim", buyingPower: 100000, availableCash: 100000, tsMs: Date.now() } });
    const linkGroups = new LinkGroups({ post: () => { }, onMessage: () => () => { }, close: () => { } }, () => { });
    linkGroups.focusVenue("green", "sim");
    const host = document.createElement("div");
    document.body.append(host);
    host.getBoundingClientRect = () => ({ x: 0, y: 0, top: 0, left: 0, right: 500, bottom: 400, width: 500, height: 400, toJSON: () => ({}) });
    const facadeRef = { current: { priceScaleWidth: () => 60, paneHeights: () => [400], coordinateToPrice: (y: number) => 12 - y / 100, priceToCoordinate: (p: number) => (12 - p) * 100 } as ChartApiFacade };
    const sendCommand = vi.fn(async (name: string, args: unknown) => { void name; void args; return { kind: "ack" as const, corrId: "1", status: "accepted" as const, orderId: "E1" }; });
    const sendQuery = vi.fn(async () => ({ route: "ENGINE_HELD", effectiveSession: "EXTENDED", phase: "RTH", deadlineMs: Date.now() + 100000, hasTrustedEligiblePrint: true, lastEligiblePrice: 9, lastEligibleTsMs: Date.now() }));
    const result = render(<ChartRiskEntry chrome={getTvChrome("light")} panelId="chart" active group="green" symbol="AAPL" contextKey="1m" hostRef={{ current: host }} facadeRef={facadeRef} stores={stores} linkGroups={linkGroups} config={{ activeVenue: "sim", templates: [template], chartRiskAutoSend: auto }} configLoaded activeTool="select" chooserOpenRef={{ current: false }} sendCommand={sendCommand} sendQuery={sendQuery}/>, { container: host });
    sendCommand.mockClear();
    return { ...result, host, sendCommand, sendQuery };
}
beforeEach(() => {
    cleanup();
    document.body.replaceChildren();
    vi.restoreAllMocks();
    vi.spyOn(document, "hasFocus").mockReturnValue(true);
    vi.stubGlobal("requestAnimationFrame", (cb: FrameRequestCallback) => { cb(0); return 0; });
    vi.stubGlobal("cancelAnimationFrame", () => { });
    vi.stubGlobal("ResizeObserver", class { observe() {} disconnect() {} });
});
it("previews two clicks and sends one risk-sized pair on Enter", async () => {
    const { host, sendCommand } = mount();
    expect(initiateChartRiskEntry(template)).toBe(true);
    fireEvent.pointerDown(host, { pointerId: 1, button: 0, clientX: 100, clientY: 200 });
    fireEvent.pointerUp(window, { pointerId: 1, button: 0, clientX: 100, clientY: 200 });
    fireEvent.pointerDown(host, { pointerId: 2, button: 0, clientX: 100, clientY: 220 });
    fireEvent.pointerUp(window, { pointerId: 2, button: 0, clientX: 100, clientY: 220 });
    const buy = host.querySelector<HTMLButtonElement>("[data-risk-price='buy']")!;
    await waitFor(() => expect(buy.title).toContain("500 planned shares"));
    expect(buy.textContent).toBe("B 10.00");
    expect(buy.title).toContain("Enter send · Esc cancel");
    expect(buy.title).not.toContain("$100.00");
    expect(host.querySelector("[data-risk-detail]")?.textContent).toBe("");
    expect(screen.getByTestId("chart-risk-entry").textContent).not.toContain("notional");
    expect(sendCommand).not.toHaveBeenCalledWith("SubmitRiskEntry", expect.anything());
    fireEvent.keyDown(window, { key: "Enter" });
    await waitFor(() => expect(sendCommand).toHaveBeenCalledWith("SubmitRiskEntry", expect.objectContaining({ buyStop: 10, sellStop: 9.8, maxQty: 500, value: 100, mode: "Dollar" })));
    fireEvent.keyDown(window, { key: "Enter" });
    expect(sendCommand.mock.calls.filter(([name]) => name === "SubmitRiskEntry")).toHaveLength(1);
});
it("auto-sends one drag on release and cancels another setup on Escape", async () => {
    const { host, sendCommand } = mount(true);
    initiateChartRiskEntry(template);
    await waitFor(() => expect(screen.getByTestId("chart-risk-entry").textContent).not.toContain("Checking engine"));
    fireEvent.pointerDown(host, { pointerId: 1, button: 0, clientX: 100, clientY: 200 });
    fireEvent.pointerMove(window, { pointerId: 1, clientX: 100, clientY: 220 });
    fireEvent.pointerUp(window, { pointerId: 1, clientX: 100, clientY: 220 });
    await waitFor(() => expect(sendCommand).toHaveBeenCalledWith("SubmitRiskEntry", expect.objectContaining({ maxQty: 500 })));
    sendCommand.mockClear();
    initiateChartRiskEntry(template);
    fireEvent.pointerDown(host, { pointerId: 2, button: 0, clientX: 100, clientY: 200 });
    fireEvent.keyDown(window, { key: "Escape" });
    expect(screen.getByTestId("chart-risk-entry").style.display).toBe("none");
    fireEvent.pointerMove(window, { pointerId: 2, clientX: 100, clientY: 220 });
    fireEvent.pointerUp(window, { pointerId: 2, clientX: 100, clientY: 220 });
    expect(sendCommand).not.toHaveBeenCalled();
});
it("keeps blockers and uncertain submission outcomes visible", async () => {
    const { host, sendCommand, sendQuery } = mount();
    sendQuery.mockRejectedValueOnce(new Error("offline"));
    initiateChartRiskEntry(template);
    await waitFor(() => expect(host.querySelector("[data-risk-status]")?.textContent).toBe("Engine preview unavailable."));
    expect(screen.queryByRole("button")).toBeNull();
    fireEvent.keyDown(window, { key: "Escape" });

    sendCommand.mockImplementation(async () => ({ kind: "ack", corrId: "1", status: "accepted", orderId: "E1", ambiguous: true }));
    initiateChartRiskEntry(template);
    fireEvent.pointerDown(host, { pointerId: 1, button: 0, clientX: 100, clientY: 200 });
    fireEvent.pointerUp(window, { pointerId: 1, clientX: 100, clientY: 200 });
    fireEvent.pointerDown(host, { pointerId: 2, button: 0, clientX: 100, clientY: 220 });
    fireEvent.pointerUp(window, { pointerId: 2, clientX: 100, clientY: 220 });
    fireEvent.keyDown(window, { key: "Enter" });
    await waitFor(() => expect(host.querySelector("[data-risk-status]")?.textContent).toContain("Submit outcome unknown"));
    expect(host.querySelector<HTMLButtonElement>("[data-risk-price='buy']")?.title).toContain("500 planned shares");
    expect(host.querySelector<HTMLButtonElement>("[data-risk-price='buy']")?.title).not.toContain("Enter send");
    fireEvent.keyDown(window, { key: "Enter" });
    expect(sendCommand.mock.calls.filter(([name]) => name === "SubmitRiskEntry")).toHaveLength(1);
});
it("drags a draft price on the axis and discards the pair from either X", async () => {
    const {host,sendCommand} = mount();
    initiateChartRiskEntry(template);
    fireEvent.pointerDown(host,{pointerId:1,button:0,clientX:100,clientY:200});
    fireEvent.pointerUp(window,{pointerId:1,clientX:100,clientY:200});
    fireEvent.pointerDown(host,{pointerId:2,button:0,clientX:100,clientY:220});
    fireEvent.pointerUp(window,{pointerId:2,clientX:100,clientY:220});
    const buy = host.querySelector<HTMLButtonElement>("[data-risk-price='buy']")!;
    fireEvent.pointerDown(buy,{pointerId:3,button:0,clientX:470,clientY:200});
    fireEvent.pointerMove(window,{pointerId:3,clientX:470,clientY:190});
    fireEvent.pointerUp(window,{pointerId:3,clientX:470,clientY:190});
    await waitFor(() => expect(buy.title).toContain("333 planned shares"));
    expect(buy.textContent).toBe("B 10.10");
    const cancel = screen.getAllByRole("button",{name:"Discard risk setup"})[1];
    fireEvent.keyDown(cancel,{key:"Enter"});
    expect(sendCommand).not.toHaveBeenCalledWith("SubmitRiskEntry",expect.anything());
    fireEvent.click(cancel);
    expect(screen.getByTestId("chart-risk-entry").style.display).toBe("none");
});
